baseURL = 'https://eliezergh.github.io/'
languageCode = "en"
defaultcontentlanguage = "en"
title = "EliezerGH"
theme = "hugo-coder"

[params]
  author = "Eliezer González"
  info = "DevOps Engineer"
  favicon_32 = "images/favicon-32x32.png"
  avatarurl = "images/avatar.png"

  colorScheme = "dark"  

[[params.social]]
  name = "Github"
  icon = "fa-brands fa-github fa-2x"
  weight = 1
  url = "https://github.com/eliezergh"
[[params.social]]
  icon = "fa-brands fa-linkedin fa-2x"
  name = "linkedin"
  weight = 2
  url = "https://www.linkedin.com/in/eliezergh"
[[params.social]]
  icon = "fa-regular fa-envelope fa-2x"
  name = "email"
  weight = 3
  url = "mailto:eliezerghtech@gmail.com"



[menu]
  [[menu.main]]
    identifier = "home"
    name = "Home"
    url = "/"
    weight = 1
  [[menu.main]]
    identifier = "blog"
    name = "Blog"
    url = "posts/"
    weight = 2
  [[menu.main]]
    identifier = "about"
    name = "About"
    url = "/about/"
    weight = 3

[services]
  [services.googleAnalytics]
    ID = 'G-YYZEFQNCGW'